bonbon_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path

from catalog import views


app_name = "catalog"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("catalog/<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("catalog/<int:pk>/<slug:slug>/", views.product_detail, name="product_detail"),

    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.UserCreateView.as_view(), name="register"),

    path("cart/", views.cart_detail, name="cart_detail"),
    path("cart/add/<int:product_id>", views.cart_add, name="cart-add"),
    path("cart/remove/<int:product_id>", views.cart_remove, name="cart-remove"),
]

templates/includes/navbar.html
{% load static %}
<div class="fixed-top nav-container glass w-75 m-auto">
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="{% static 'logo/logo.png' %}" alt="logo" width="30" height="30" class="d-inline-block align-text-top">
        BonBon
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'catalog:product_list' %}">Catalog</a>
          </li>

          <!--#region categories dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'catalog:product_list' %}">All</a>
              </li>

              {% for c in categories %}
                <li class="nav-item">
                  <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                </li>
              {% endfor %}
            </ul>
          </li>
          <!--#endregion -->

          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>

          <!--#region cart link -->
          <li class="nav-item">
            {% with total_items=cart|length %}
              {% if total_items > 0 %}

                <a class="nav-link" href="{% url "catalog:cart_detail" %}">
                  Your cart:
                  {{ total_items }} item{{ total_items|pluralize }},
                  ${{ cart.get_total_price }}
                </a>
              {% else %}
                <a class="nav-link" href="#">Your cart is empty</a>
              {% endif %}

            {% endwith %}
            <!--#endregion -->
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Welcome {{ user.username }}!</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'catalog:logout' %}">Logout</a>
              </li>

            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'catalog:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'catalog:register' %}">Register</a>
              </li>
            {% endif %}



        </ul>
      </div>
    </div>
  </nav>
</div>

templates/includes/sidebar.html
<div class="nav-container mb-4">
<ul class="nav nav-pills flex-column">
  <li class="nav-item">
    <p class="nav-link disabled"><strong>Categories</strong></p>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if not category %}active{% endif %}" href="{% url 'catalog:product_list' %}">All</a>
  </li>

  {% for c in categories %}
    <li class="nav-item">
      <a class="nav-link {% if category.slug == c.slug %}active{% endif %}"
         href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
    </li>
  {% endfor %}
</ul>
</div>