bonbon_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path

from catalog import views


app_name = "catalog"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("catalog/<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("catalog/<int:pk>/<slug:slug>/", views.product_detail, name="product_detail"),

    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.UserCreateView.as_view(), name="register"),

    path("cart/", views.cart_detail, name="cart_detail"),
    path("cart/add/<int:product_id>", views.cart_add, name="cart-add"),
    path("cart/remove/<int:product_id>", views.cart_remove, name="cart-remove"),
]

catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from catalog.utils import product_directory_path


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("catalog:product_list_by_category", args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="products"
    )
    image = models.ImageField(upload_to=product_directory_path, blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("catalog:product_detail", args=[self.pk, self.slug])


class User(AbstractUser):
    city = models.CharField(max_length=100)
    cart = models.OneToOneField("Cart", on_delete=models.SET_NULL, null=True, blank=True, related_name="owner")

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Order(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="orders")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    products = models.ManyToManyField(Product, through="OrderItem", related_name="orders")

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="order_items")
    price = models.DecimalField(max_digits=5, decimal_places=2)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.pk

    def get_cost(self):
        return self.price * self.quantity


class Cart(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    products = models.ManyToManyField(Product, through="CartItem", related_name="carts")

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="cart_items")
    price = models.DecimalField(max_digits=5, decimal_places=2)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.product.name

    def get_cost(self):
        return self.price * self.quantity

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter a valid username"
            }
        )
    )
    password = forms.CharField(
        max_length=255,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter password"
            }
        )
    )


class RegistrationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "first_name", "last_name", "email", "city")


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        label="",
        coerce=int
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )
    redirect_url = forms.CharField(
        required=False,
        widget=forms.HiddenInput
    )

    class Meta:
        fields = ("quantity", "override")

catalog/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.http import require_POST

from catalog.forms import CartAddProductForm, LoginForm, RegistrationForm
from catalog.models import Category, Product, Cart, CartItem
from catalog.services.anonymous_cart import AnonymousCart


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {
        "category": category,
        "categories": categories,
        "products": products,
    }
    return render(request, "catalog/product_list.html", context=context)


def product_detail(request, pk, slug):
    categories = Category.objects.all()
    product = get_object_or_404(Product, pk=pk, slug=slug, available=True)
    form = CartAddProductForm()
    context = {"categories": categories, "product": product, "cart_product_form": form}
    return render(request, "catalog/product_detail.html", context=context)


def login_view(request):
    if request.user.is_authenticated:
        messages.info(request, "You are already logged in")
        return redirect("catalog:product_list")

    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            print("is valid")
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if not user:
                messages.error(request, "Invalid login or password")

                return redirect("catalog:login")

            login(request, user)
            cart = AnonymousCart(request)

            if not user.cart or not user.cart.items.all():
                if not user.cart:
                    user.cart = Cart.objects.create()
                for product_id, item in cart.cart.items():
                    product = Product.objects.get(pk=product_id)
                    CartItem.objects.create(
                        cart=user.cart,
                        product=product,
                        price=Decimal(item["price"]),
                        quantity=item["quantity"],
                    )
                user.save()
            else:
                cart.clear()
                cart = AnonymousCart(request)
                for item in user.cart.items.all():
                    cart.add(item.product, item.quantity)

            return redirect("catalog:product_list")
        else:
            print("not valid")
            return render(request, "accounts/login.html", {"form": form})

    form = LoginForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context=context)


@login_required
def logout_view(request):
    logout(request)
    return redirect("catalog:product_list")


class UserCreateView(generic.CreateView):
    model = get_user_model()
    form_class = RegistrationForm
    template_name = "accounts/register.html"
    success_url = reverse_lazy("catalog:login")


@require_POST
def cart_add(request, product_id):
    cart = AnonymousCart(request)
    product = get_object_or_404(Product, pk=product_id, available=True)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cart.add(product, form.cleaned_data["quantity"], form.cleaned_data["override"])

    if request.user.is_authenticated:
        if request.user.cart.items.filter(product=product).exists():
            print("item exist")
            cart_item = request.user.cart.items.get(product=product)
            if form.cleaned_data["override"]:
                cart_item.quantity = form.cleaned_data["quantity"]
            else:
                cart_item.quantity += form.cleaned_data["quantity"]
            cart_item.save()
            print(cart_item.quantity)
        else:
            print("create new item")
            CartItem.objects.create(
                cart=request.user.cart,
                product=product,
                price=product.price,
                quantity=form.cleaned_data["quantity"],
            )

    if form.cleaned_data["redirect_url"]:
        return redirect(form.cleaned_data["redirect_url"])
    return redirect("catalog:cart_detail")


@require_POST
def cart_remove(request, product_id):
    cart = AnonymousCart(request)
    product = get_object_or_404(Product, pk=product_id, available=True)
    cart.remove(product)
    if request.user.is_authenticated:
        request.user.cart.items.get(product=product).delete()
    return redirect("catalog:cart_detail")


def cart_detail(request):
    cart = AnonymousCart(request)
    context = {"cart": cart}
    return render(request, "catalog/cart_detail.html", context=context)

templates/catalog/cart_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Cart{% endblock %}


{% block content %}

  <h1>Cart</h1>

  {% for item in cart %}
    {% with product=item.product %}

      <div class="card mb-3 w-100">
        <div class="row g-0">
          <div class="col-md-10">
            <div class="card-body h-100">
              <div class="d-flex justify-content-between">
                <h3 class="card-title">{{ product.name }} x {{ item.quantity }}</h3>
                <h4 class="card-title">${{ product.price }}</h4>
              </div>
              <h6 class="card-subtitle mb-2 text-body-secondary">{{ product.category|title }}</h6>
              {#              <p class="card-text">{{ product.description }}</p>#}
              <div class="d-flex mb-3 position-absolute absolute-bottom width-100">
                <div class="p-2">
{#                  <a class="btn btn-glass" href="{{ product.get_absolute_url }}">Remove</a>#}
                  <form action="{% url 'catalog:cart-remove' product.id %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-glass" type="submit" value="Remove">
                    
                  </form>
                </div>
                <div class="p-2">
                  <a class="btn btn-glass" href="{{ product.get_absolute_url }}">Update</a>
                </div>
                <div class="p-2 ms-auto">
                  <h4 class="card-title">Price: {{ item.total_price }}$</h4>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-2 d-flex">
            <img class="img-fluid w-100 m-1 align-self-center rounded"
                 src="{% if product.image %}{{ product.image.url }}
                  {% else %}{% static 'img/no_image.jpg' %}
                  {% endif %}"  alt="product image">
          </div>
        </div>
      </div>

    {% endwith %}
  {% endfor %}

  <div class="card mb-3 w-100">
    <div class="card-body">
      
      <h3 class="card-title">Total: {{ cart.get_total_price }}$</h3>
      <a class="btn btn-success m-2" href="#">Checkout</a>
      <a class="btn btn-glass" href="{% url 'catalog:product_list' %}">Continue shopping</a>

    </div>
  </div>

{% endblock %}

templates/catalog/product_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
  <h1>Product detail</h1>
  <div class="card mb-3 w-100">
    <div class="row g-0">
      <div class="col-md-8">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <h1 class="card-title">{{ product.name }}</h1>
            <h2 class="card-title">${{ product.price }}</h2>
          </div>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{ product.category|title }}</h6>
          <p class="card-text">{{ product.description }}</p>
          <p class="card-text"><small class="text-body-secondary">Last updated: {{ product.updated }}</small></p>
          <form class="w-25" action="{% url 'catalog:cart-add' product.pk %}" method="post">
            {% csrf_token %}
            {{ cart_product_form|crispy }}
            <div>
              <label for="override">Override?</label>
              <input id="override" type="checkbox" name="override" value="override">
            </div>
            <br>
            <input class="btn btn-glass" type="submit" value="Add to cart">
            <input type="hidden" name="redirect_url" value="{{ product.get_absolute_url }}">
          </form>
        </div>
      </div>
      <div class="col-md-4">
        <img src="{% if product.image %}{{ product.image.url }}
                  {% else %}{% static 'img/no_image.jpg' %}
                  {% endif %}" class="img-fluid rounded-start" alt="...">
      </div>
    </div>
  </div>

{% endblock %}

templates/catalog/product_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name|title }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  
  <h1>
    {% if category %}{{ category.name|title }}
    {% else %}All{% endif %}
  </h1>

  {% for product in products %}
    <div class="col-sm-6 col-lg-4">
      <div class="card mb-4">
        <img class="card-img-top"
             alt="dessert picture"
             src="{% if product.image %}{{ product.image.url }}
                  {% else %}{% static 'img/no_image.jpg' %}
                  {% endif %}">

        <div class="card-body">
          <div class="d-flex justify-content-between">
            <h5 class="card-title">"{{ product.name|title }}"</h5>
            <h5 class="card-title">${{ product.price }}</h5>
          </div>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{ product.category|title }}</h6>
          <p class="card-text">{{ product.description }}</p>
          <p class="ca"></p>
          <div class="d-flex justify-content-between">
          <a class="btn btn-link" href="{{ product.get_absolute_url }}">Details</a>
            <form action="{% url 'catalog:cart-add' product.pk %}" method="post">
              {% csrf_token %}
              <input class="btn btn-glass" type="submit" value="Add to cart">
              <input type="hidden" name="quantity" value="1">
              <input type="hidden" name="redirect_url" value="{% url 'catalog:cart_detail' %}">
            </form>
          </div>
          
        </div>

      </div>
    </div>
  {% endfor %}

{% endblock %}